name: Deploy Frontend to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kódu
        uses: actions/checkout@v3

      - name: Pripojenie cez SSH a spustenie deploy skriptu
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            bash /home/apps/car_rental_frontend/deploy_frontend.sh
